######################################################################
# Automatically generated by qmake (2.01a) Thu Oct 11 11:59:29 2012
######################################################################

TEMPLATE = app
TARGET = MyChessGame

# Directories
OBJECTS_DIR = .obj
MOC_DIR = .moc
RCC_DIR = .rcc

RESOURCES += \
    resources/figures.qrc
